=== supeffective/assets/data/schemas/pokemon-entry.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "nid": {
            "type": "string",
            "pattern": "^[0-9a-z-]+$"
        },
        "dexNum": {
            "type": "integer"
        },
        "formId": {
            "type": [
                "string",
                "null"
            ]
        },
        "name": {
            "type": "string"
        },
        "formName": {
            "type": [
                "string",
                "null"
            ]
        },
        "region": {
            "type": "string"
        },
        "generation": {
            "type": "integer"
        },
        "type1": {
            "$ref": "#/$defs/typeId"
        },
        "type2": {
            "oneOf": [
                {
                    "$ref": "#/$defs/typeId"
                },
                {
                    "type": "null"
                }
            ]
        },
        "color": {
            "type": "string"
        },
        "abilities": {
            "type": "object",
            "properties": {
                "primary": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "secondary": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "hidden": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "required": [
                "primary",
                "secondary",
                "hidden"
            ]
        },
        "isLegendary": {
            "type": "boolean"
        },
        "isMythical": {
            "type": "boolean"
        },
        "isUltraBeast": {
            "type": "boolean"
        },
        "ultraBeastCode": {
            "type": [
                "string",
                "null"
            ]
        },
        "isDefault": {
            "type": "boolean"
        },
        "isForm": {
            "type": "boolean"
        },
        "isSpecialAbilityForm": {
            "type": "boolean"
        },
        "isCosmeticForm": {
            "type": "boolean"
        },
        "isFemaleForm": {
            "type": "boolean"
        },
        "hasGenderDifferences": {
            "type": "boolean"
        },
        "isBattleOnlyForm": {
            "type": "boolean"
        },
        "isSwitchableForm": {
            "type": "boolean"
        },
        "isFusion": {
            "type": "boolean"
        },
        "fusedWith": {
            "type": "null"
        },
        "isMega": {
            "type": "boolean"
        },
        "isPrimal": {
            "type": "boolean"
        },
        "isRegional": {
            "type": "boolean"
        },
        "isGmax": {
            "type": "boolean"
        },
        "canGmax": {
            "type": "boolean"
        },
        "canDynamax": {
            "type": "boolean"
        },
        "canBeAlpha": {
            "type": "boolean"
        },
        "debutIn": {
            "$ref": "#/$defs/gameSetId"
        },
        "obtainableIn": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/gameSetId"
            }
        },
        "onlyViaEventIn": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/gameSetId"
            }
        },
        "storableIn": {
            "type": "array",
            "items": {
                "$ref": "#/$defs/gameSetId"
            }
        },
        "shinyReleased": {
            "type": "boolean"
        },
        "baseStats": {
            "type": "object",
            "properties": {
                "hp": {
                    "type": "integer"
                },
                "atk": {
                    "type": "integer"
                },
                "def": {
                    "type": "integer"
                },
                "spa": {
                    "type": "integer"
                },
                "spd": {
                    "type": "integer"
                },
                "spe": {
                    "type": "integer"
                }
            },
            "required": [
                "hp",
                "atk",
                "def",
                "spa",
                "spd",
                "spe"
            ]
        },
        "goStats": {
            "type": "object",
            "properties": {
                "maxCP": {
                    "type": "integer"
                },
                "attack": {
                    "type": "integer"
                },
                "defense": {
                    "type": "integer"
                },
                "stamina": {
                    "type": "integer"
                }
            },
            "required": [
                "maxCP",
                "attack",
                "defense",
                "stamina"
            ]
        },
        "weight": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "string"
                },
                "min": {
                    "type": "string"
                },
                "max": {
                    "type": "string"
                },
                "alpha": {
                    "type": "string"
                }
            },
            "required": [
                "avg",
                "min",
                "max",
                "alpha"
            ]
        },
        "height": {
            "type": "object",
            "properties": {
                "avg": {
                    "type": "string"
                },
                "min": {
                    "type": "string"
                },
                "max": {
                    "type": "string"
                },
                "alpha": {
                    "type": "string"
                }
            },
            "required": [
                "avg",
                "min",
                "max",
                "alpha"
            ]
        },
        "maleRate": {
            "type": "integer"
        },
        "femaleRate": {
            "type": "integer"
        },
        "refs": {
            "type": "object",
            "properties": {
                "pogo": {
                    "type": "string"
                },
                "veekunDb": {
                    "type": "string"
                },
                "serebii": {
                    "type": "string"
                },
                "bulbapedia": {
                    "type": "string"
                },
                "homeSprite": {
                    "type": "string"
                },
                "miniSprite": {
                    "type": "string"
                },
                "showdown": {
                    "type": "string"
                },
                "showdownDef": {
                    "type": "string"
                },
                "smogon": {
                    "type": "string"
                }
            },
            "required": [
                "pogo",
                "veekunDb",
                "serebii",
                "bulbapedia",
                "homeSprite",
                "miniSprite",
                "showdown",
                "showdownDef",
                "smogon"
            ]
        },
        "baseSpecies": {
            "type": [
                "string",
                "null"
            ]
        },
        "baseForms": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "forms": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "evolutions": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "id",
        "nid",
        "dexNum",
        "formId",
        "name",
        "formName",
        "region",
        "generation",
        "type1",
        "type2",
        "color",
        "abilities",
        "isLegendary",
        "isMythical",
        "isUltraBeast",
        "ultraBeastCode",
        "isDefault",
        "isForm",
        "isSpecialAbilityForm",
        "isCosmeticForm",
        "isFemaleForm",
        "hasGenderDifferences",
        "isBattleOnlyForm",
        "isSwitchableForm",
        "isFusion",
        "fusedWith",
        "isMega",
        "isPrimal",
        "isRegional",
        "isGmax",
        "canGmax",
        "canDynamax",
        "canBeAlpha",
        "debutIn",
        "obtainableIn",
        "onlyViaEventIn",
        "storableIn",
        "shinyReleased",
        "baseStats",
        "goStats",
        "weight",
        "height",
        "maleRate",
        "femaleRate",
        "refs",
        "baseSpecies",
        "baseForms",
        "forms",
        "evolutions"
    ],
    "$defs": {
        "typeId": {
            "type": "string",
            "enum": [
                "normal",
                "fire",
                "water",
                "electric",
                "grass",
                "ice",
                "fighting",
                "poison",
                "ground",
                "flying",
                "psychic",
                "bug",
                "rock",
                "ghost",
                "dragon",
                "dark",
                "steel",
                "fairy"
            ]
        },
        "gameSetId": {
            "type": "string",
            "enum": [
                "rb",
                "y",
                "gs",
                "c",
                "rs",
                "frlg",
                "e",
                "dp",
                "pt",
                "hgss",
                "bw",
                "b2w2",
                "xy",
                "oras",
                "go",
                "sm",
                "usum",
                "lgpe",
                "swsh",
                "home",
                "bdsp",
                "la",
                "sv"
            ]
        }
    }
}

=== supeffective/assets/data/sources/pokemon/entries/grumpig.json
{
    "id": "grumpig",
    "nid": "0326",
    "dexNum": 326,
    "formId": null,
    "name": "Grumpig",
    "formName": null,
    "region": "hoenn",
    "generation": 3,
    "type1": "psychic",
    "type2": null,
    "color": "purple",
    "abilities": {
        "primary": null,
        "secondary": null,
        "hidden": null
    },
    "isLegendary": false,
    "isMythical": false,
    "isUltraBeast": false,
    "ultraBeastCode": null,
    "isDefault": true,
    "isForm": false,
    "isSpecialAbilityForm": false,
    "isCosmeticForm": false,
    "isFemaleForm": false,
    "hasGenderDifferences": false,
    "isBattleOnlyForm": false,
    "isSwitchableForm": false,
    "isFusion": false,
    "fusedWith": null,
    "isMega": false,
    "isPrimal": false,
    "isRegional": false,
    "isGmax": false,
    "canGmax": false,
    "canDynamax": true,
    "canBeAlpha": false,
    "debutIn": "rs",
    "obtainableIn": [
        "bdsp",
        "e",
        "go",
        "oras",
        "rs"
    ],
    "onlyViaEventIn": [],
    "storableIn": [
        "b2w2",
        "bdsp",
        "bw",
        "dp",
        "e",
        "frlg",
        "go",
        "hgss",
        "home",
        "oras",
        "pt",
        "rs",
        "sm",
        "usum",
        "xy"
    ],
    "shinyReleased": true,
    "baseStats": {
        "hp": -1,
        "atk": -1,
        "def": -1,
        "spa": -1,
        "spd": -1,
        "spe": -1
    },
    "goStats": {
        "maxCP": -1,
        "attack": -1,
        "defense": -1,
        "stamina": -1
    },
    "weight": {
        "avg": "-1kg",
        "min": "-1kg",
        "max": "-1kg",
        "alpha": "-1kg"
    },
    "height": {
        "avg": "-1m",
        "min": "-1m",
        "max": "-1m",
        "alpha": "-1m"
    },
    "maleRate": -1,
    "femaleRate": -1,
    "refs": {
        "pogo": "GRUMPIG",
        "veekunDb": "grumpig",
        "serebii": "grumpig",
        "bulbapedia": "Grumpig",
        "homeSprite": "grumpig",
        "miniSprite": "grumpig",
        "showdown": "grumpig",
        "showdownDef": "Grumpig",
        "smogon": "grumpig"
    },
    "baseSpecies": null,
    "baseForms": [],
    "forms": [
        "grumpig"
    ],
    "evolutions": []
}
